### ISSUE TITLE
💡 [REQUEST] - We should check for dependencies for building from source

### ISSUE THREAD

**Issue by tylercritchlow** [brodycritchlow/winch#15]
### Start Date

Future

### Summary

There should be steps to install dependencies for each OS in `config.winch`

### Basic Example

```toml
#...
[dependencies]
apt = "sudo apt install gcc"
dnf = "sudo dnf install gcc"
pacman = "sudo pacman -S gcc"
windows = "https:/link.com"
```
### Drawbacks

N/A
